export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const GET_REPOSITORIES_SUCCESS = 'GET_REPOSITORIES_SUCCESS';
export const GET_REPOSITORIES_ERROR = 'GET_REPOSITORIES_ERROR';

export const GET_LICENSES = 'GET_LICENSES';
export const GET_LICENSES_SUCCESS = 'GET_LICENSES_SUCCESS';
export const GET_LICENSES_ERROR = 'GET_LICENSES_ERROR';
