name: CD
on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: reifter/github-javascript-repositories@development
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/rkul.ru/github-javascript-repositories
          git checkout development
          git pull origin development
          git status
          npm install --only=prod

